name: Bump Version

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Install Gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: "Configure Git"
      run: |
        git config --global user.email ${OWNER}@users.noreply.github.com
        git config --global user.name ${OWNER}

    - name: "Bump Version"
      run: |
        bundle exec gem bump
        bundle exec gem tag

    - name: "Push"
      run: |
        git remote set-url --push origin https://$OWNER:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git push --set-upstream origin
        git push --tags --set-upstream origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
