name: Bump Version Number

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Bump Version Number
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: "Configure Git"
      run: |
        git config --global user.email "elliotthilaire-ca@users.noreply.github.com"
        git config --global user.name "eliotthilaire-ca"
        git checkout -b master

    - name: "Bump the version"
      run: |
        bundle exec gem bump

    - name: "Push"
      run: |
        git remote set-url --push origin https://elliotthilaire-ca:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        git push --set-upstream origin
        git push --set-upstream origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
