name: Prerelease workflow

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch to publish from'
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }} 
           
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'        

    - name: Install Gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Ensure gem has prerelease version number
      run: |
        ruby -e '
          gemspec_files = Dir["*.gemspec"]
          raise "More than one gemspec file is present #{gemspec_files}. Temporarily rename the others and re-run this action again to deploy a canary release." unless gemspec_files.one?
          version = Gem::Specification::load(gemspec_files.first).version.to_s
  
          if version.match?(/^.*\p{L}.*$/) # https://regex101.com/r/r7USwl
            puts "#{version} is a valid prerelease version number"
          else 
            puts "#{version} is not a prerelease version number. Ensure #{version} has been bumped and includes a [prerelease segment](https://guides.rubygems.org/patterns/#prerelease-gems)."
            exit 1
          end
        ' >> $GITHUB_STEP_SUMMARY

    - name: Publish to GitHub Package Repository
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.GITHUB_TOKEN}}
        OWNER: elliotthilaire-ca
